### ISSUE TITLE
Getting access to accelerometer setRange

### ISSUE THREAD

**Issue by gingemonster** [bbcmicrobit/micropython#327] opened 2016-07-21 19:43 UTC
It would be great if we could have access to setRange and getRange from the accelerometer

https://lancaster-university.github.io/microbit-docs/ubit/accelerometer/

**Comment by dpgeorge** [comment] 2016-07-22 09:04
Duplicate of: #264 #266 #306

**Closed by dpgeorge** 2016-07-22 09:04 UTC
