### ISSUE TITLE
pin0.write_analog stops working after music.play()

### ISSUE THREAD

**Issue by deshipu** [bbcmicrobit/micropython#337] opened 2016-08-09 15:20 UTC
After the following code:

```
>>> from microbit import *
>>> import music
>>> pin0.set_analog_period(20)
>>> pin0.write_analog(512)
```

I get the following result:
![img_20160809_171645](https://cloud.githubusercontent.com/assets/1181357/17521950/8854a776-5e55-11e6-8cc7-1aad19040079.jpg)

Then after this:

```
>>> music.play(music.WAWAWAWAA)
>>> pin0.write_analog(512)     
```

I get no output on pin0:
![img_20160809_171731](https://cloud.githubusercontent.com/assets/1181357/17521972/9a17e860-5e55-11e6-83b1-adf8322b1576.jpg)

**Comment by deshipu** [comment] 2016-08-09 15:25
Using ``speech.say()`` in place of ``music.play()`` doesn't have that effect.

**Comment by carlosperate** [comment] 2018-03-20 20:41
I've just tested this with a speaker and oscilloscope with version 0.9 (the one on the online editor since October 2016) and  while #345 did fix this in a way (`pin0.write_analog()` works fine after `music.play()`), something has caused the `music.play(music.WAWAWAWAA)` to not reproduce the tune output on pin0, basically the first `pin0.write_analog()` continues uninterrupted.

I've tested the same with the latest master (with the version1 branch merged) and I can confirm this version works as expected:
*  `pin0.write_analog()` produces the correct output
* `music.play(music.WAWAWAWAA)` plays the tune as expected
* second `pin0.write_analog()` works again, however, this second `write_analog` uses the period last configured by the music module.

We haven't really defined any default period for the `write_analog` so I would consider this expected behaviour.

Both issues are fixed on master, so I'll close this one.

**Closed** 2018-03-20 20:43 UTC
Labels: bug
