### ISSUE TITLE
MicroBitImage.blit - no attribute

### ISSUE THREAD

**Issue by DavidWhaleMEF** [bbcmicrobit/micropython#483] opened 2018-01-12 13:56 UTC
mu: 0.9.13

The docs state that MicroBitImage has a blit() operation, but the installed and public version of MicroPython does not support this operation.

```
>>> TRACE = Image('00000:00000:00000:90000:99990:00090:00090:00090:00090:00090:')
>>> i = Image()
>>> i.blit(TRACE, 0,0,5,5,0,0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'MicroBitImage' object has no attribute 'blit'
>>> dir(i)
['width', 'height', 'get_pixel', 'set_pixel', 'shift_left', 'shift_right', 'shift_up', 'shift_down', 'copy', 'crop', 'invert', 'HEART', 'HEART_SMALL', 'HAPPY', 'SMILE', 'SAD', 'CONFUSED', 'ANGRY', 'ASLEEP', 'SURPRISED', 'SILLY', 'FABULOUS', 'MEH', 'YES', 'NO', 'CLOCK12', 'CLOCK1', 'CLOCK2', 'CLOCK3', 'CLOCK4', 'CLOCK5', 'CLOCK6', 'CLOCK7', 'CLOCK8', 'CLOCK9', 'CLOCK10', 'CLOCK11', 'ARROW_N', 'ARROW_NE', 'ARROW_E', 'ARROW_SE', 'ARROW_S', 'ARROW_SW', 'ARROW_W', 'ARROW_NW', 'TRIANGLE', 'TRIANGLE_LEFT', 'CHESSBOARD', 'DIAMOND', 'DIAMOND_SMALL', 'SQUARE', 'SQUARE_SMALL', 'RABBIT', 'COW', 'MUSIC_CROTCHET', 'MUSIC_QUAVER', 'MUSIC_QUAVERS', 'PITCHFORK', 'XMAS', 'PACMAN', 'TARGET', 'ALL_CLOCKS', 'ALL_ARROWS', 'TSHIRT', 'ROLLERSKATE', 'DUCK', 'HOUSE', 'TORTOISE', 'BUTTERFLY', 'STICKFIGURE', 'GHOST', 'SWORD', 'GIRAFFE', 'SKULL', 'UMBRELLA', 'SNAKE']
>>> 
```

**Comment by DavidWhaleMEF** [comment] 2018-01-12 13:57
@carlosperate I recall that you moved the label on the published docs recently to make the docs match the current public release of MicroPython - can you double check that the label is correct and that the docs for the matching public release are in step please, as this problem above indicates that docs and code are still out of step. Thanks.

cc @jaustin

**Comment by DavidWhaleMEF** [comment] 2018-01-12 13:58
Here is what the docs currently say. This does not match with the reality of what the current public release of MicroPython offers.

![screen shot 2018-01-12 at 13 57 55](https://user-images.githubusercontent.com/25079586/34878065-aa0c1f08-f7a0-11e7-9826-c507c92c68e2.png)

**Comment by ntoll** [comment] 2018-01-12 14:07
Looking at the current docs on RTD... they're completely out of date, missing a large part of the tutorial I wrote and likely completely inconsistent with other aspects of MicroPython.

Someone (who) changed the, to a *really old* 0.9 version. I've updated the settings so they're now pointing at latest.

**Comment by markshannon** [comment] 2018-01-12 14:15
The problem isn't the docs, but that the version of MicroPython is really out of date.
The blit method was committed a year ago in bfbfe87b

**Comment by DavidWhaleMEF** [comment] 2018-01-12 14:17
@ntoll @carlosperate @markshannon Whatever the reason, we need the docs to always be in step with the version of code deployed at python.microbit.org and codewith.mu (current 0.9.13 for Mu)
No idea for python.microbit.org (the URL says /v/1 but I have no idea what version of code or docs that relates to - how do we check?)

**Comment by markshannon** [comment] 2018-01-12 14:20
> Whatever the reason, we need the docs to always be in step with the version of code deployed at python.microbit.org

Absolutely, yes.
But isn't that a microbit.org issue? They should deploy the docs and executable built from the same checkout.

**Comment by DavidWhaleMEF** [comment] 2018-01-12 14:42
For some reason @carlosperate tried to move the tag, but I don't think he had access to do that. @ntoll can you make sure that @carlosperate has the necessary access rights please? Thanks.

**Comment by ntoll** [comment] 2018-01-12 14:43
@DavidWhaleMEF access rights to what? You either mean to the Git repos or the ReadTheDocs setup... hard to tell which you mean. ;-) (Happy to do so once I know.)

**Comment by ntoll** [comment] 2018-01-12 14:44
FYI... I'm no longer have admin rights on this repos -- you'll have to ask @dpgeorge.

**Comment by jaustin** [comment] 2018-01-12 18:02
I can also add @microbit-carlos, @dpgeorge it's your project though so gimmie and Ack and I'll do the admin :)

**Comment by deshipu** [comment] 2018-01-13 09:05
> Someone (who?) changed the, to a really old 0.9 version. I've updated the settings so they're now pointing at latest.

I did that, because I was asked to do it, and because it made sense. It
doesn't matter what awesome new features Micro:bit MicroPython has — as
long as they are not released they are useless for the average users.
The people who can compile and flash the newest version from the
repository can also find the version selector on Readthedocs, I think.
For all the rest, defaulting to what they are actually using makes the
most sense.

We had several posts in here and on the list already asking about things that are in the docs but
don't actually exist in the released versions. Making the released version of
the docs the default fixes that.

If you have some version-independent changes in the documentation that you
would like to make available anyways, I think it would be best to backport it.

**Comment by ntoll** [comment] 2018-01-13 09:14
@deshipu aha... I'd totally missed that. I wasn't trying to point fingers...! ;-)

Ultimately, we need the work from @dpgeorge to be released so *everything* (docs and code) is up to date -- there's a lot of unreleased work that's happened over the past 18 months, it's a shame it's not being used. I think we're waiting on @jaustin to give guidance to Damien for what things need fixing.

**Comment by microbit-carlos** [comment] 2018-03-08 13:51
Created https://github.com/bbcmicrobit/micropython/issues/498 to make sure we have the correct default docs until v1.0 is released.

**Closed by microbit-carlos** 2018-03-08 13:51 UTC
Labels: docs
